const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const html=fs.readFileSync(require('node:path').join(__dirname,'../index.html'),'utf8');
const start=html.indexOf('function saturatedFatDailyLimit(');
const end=html.indexOf('const KRAXES_INSIGHT_ENERGY_KCAL_PER_KG',start);
assert(start>0&&end>start);
const code=`const data={goals:{weekday:2000,saturday:2000,sunday:2000},meals:[]};
const n=v=>Number(v)||0;
const today=()=> '2026-09-26';
const goalForDate=ds=>{const day=new Date(ds+'T12:00:00').getDay();return day===6?data.goals.saturday:day===0?data.goals.sunday:data.goals.weekday};
const weekDates=ds=>{const d=new Date(ds+'T12:00:00'),shift=(d.getDay()+6)%7;d.setDate(d.getDate()-shift);return Array.from({length:7},(_,i)=>{const day=new Date(d);day.setDate(d.getDate()+i);return day.toISOString().slice(0,10)})};
${html.slice(start,end)}
({data,saturatedFatDailyLimit,summarizeSaturatedFatWeek})`;
const {data,saturatedFatDailyLimit,summarizeSaturatedFatWeek}=vm.runInNewContext(code);
const near=(actual,expected)=>assert(Math.abs(actual-expected)<.001,`${actual} ≠ ${expected}`);
near(saturatedFatDailyLimit('2026-09-21'),2000*.1/9);
near(summarizeSaturatedFatWeek('2026-09-21').saturatedFatWeeklyLimit,2000*.1/9*7);
for(const key of ['weekday','saturday','sunday'])data.goals[key]=1750;
near(saturatedFatDailyLimit('2026-09-21'),1750*.1/9);
near(summarizeSaturatedFatWeek('2026-09-21').saturatedFatWeeklyLimit,1750*.1/9*7);
data.goals.saturday=2000;
near(summarizeSaturatedFatWeek('2026-09-21').saturatedFatWeeklyLimit,(1750*6+2000)*.1/9);
const meals=[{date:'2026-09-21',satFat:25},{date:'2026-09-22',satFat:5}];
let result=summarizeSaturatedFatWeek('2026-09-21',meals,'2026-09-23');
assert.equal(result.saturatedFatConsumed,30);
assert.equal(result.saturatedFatDailyAverage,15);
assert.equal(result.saturatedFatDaysIncluded,2);
assert.equal(result.isComplete,false);
assert.equal(result.isolatedHighDays.length,1);
result=summarizeSaturatedFatWeek('2026-09-21',[...meals,{date:'2026-09-22'}],'2026-09-23');
assert.equal(result.saturatedFatConsumed,null);
assert.equal(result.saturatedFatDailyAverage,null);
assert.equal(result.saturatedFatPercentOfWeeklyLimit,null);
assert.equal(result.saturatedFatMissingEntries,1);
const full=Array.from({length:7},(_,i)=>({date:`2026-09-${String(21+i).padStart(2,'0')}`,satFat:10}));
result=summarizeSaturatedFatWeek('2026-09-21',full,'2026-09-28');
assert.equal(result.isComplete,true);
assert.equal(result.saturatedFatConsumed,70);
assert.equal(data.meals.length,0);
console.log('Saturated fat: dynamic goals, mixed week, partial week, isolated high day, missing history and completed week OK');
